---
title: "HTML Report project"
output: html_document
date: "2023-01-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(flexdashboard)
library(naniar)
library(janitor)
library(simputation)
wd = "C:/Users/sebas/Desktop/Projet Thyroid"
setwd(wd)
thyroid <- read.csv('thyroid.csv')
```



```{r}
skimr::skim(thyroid)
```

```{r}
head(thyroid)
```



```{r}
thyroid <- clean_names(thyroid) 
colnames(thyroid)[1] <- 'thyroid_class'
thyroid[15,'patient_age'] <- 28
thyroid[15,3:28] <- c(0,thyroid[15,3:27])
thyroid[15,]
thyroid[,'fti_reading'] <- as.numeric(thyroid[,'fti_reading'])
thyroid[,'patient_age'] <- as.numeric(thyroid[,'patient_age'])
head(thyroid)
```



Missing variables

```{r}
thyroid <- impute_rf(thyroid, tsh_reading ~ . ) %>%
  impute_rf(t3_reading ~ .) %>%
  impute_rf(t4_reading ~ .) %>%
  impute_rf(thyrox_util_rate_t4u_reading ~ .) %>%
  impute_rf(fti_reading ~ .)

```

```{r}
skimr::skim(thyroid)
```

```{r}
p <- ggplot(data = thyroid) + geom_point(mapping = aes(x = tsh_reading, y = thyroid_class, color = ref_src))  
plotly::ggplotly()
```

```{r}
ggplot(data = thyroid) + geom_point(mapping = aes(x = t4_reading, y = thyroid_class))  
```

```{r}
ggplot(data = thyroid) + geom_point(mapping = aes(x = thyrox_util_rate_t4u_reading, y = thyroid_class))  
```

```{r}
p <- ggplot(data = thyroid, mapping = aes(x = t3_reading, y = tsh_reading, color = thyroid_class)) + geom_point() 

plotly::ggplotly(p)
```

```{r}
p <- ggplot(data = thyroid, mapping = aes(x = t3_reading , y = tsh_reading, color = thyroid_class)) + geom_point() 
p <- p + facet_grid(. ~ ref_src)
plotly::ggplotly(p)
```

```{r}
ggplot(data = thyroid, mapping = aes(x = radioactive_iodine_therapy_i131, fill = thyroid_class)) + geom_bar()
```

```{r}
p <- ggplot(data = thyroid, mapping = aes(x = goitre, fill = thyroid_class)) + geom_bar()
plotly::ggplotly(p)

```

```{r}
ggplot(data = thyroid) + geom_point(mapping = aes(x = tsh_reading, y = goitre))  

```

```{r}
p <- ggplot(data = thyroid, mapping = aes(x = tumor, fill = thyroid_class)) + geom_bar()
plotly::ggplotly(p)
```








```{r}

thyroid %>%
  select(., thyroid_class, patient_age) %>%
  filter(thyroid_class == 'sick') %>%
  group_by(thyroid_class, patient_age) %>%
  ggplot() + geom_density(aes(x = patient_age))
```

```{r}
p <- ggplot(data = filter(thyroid, 60 < patient_age & patient_age < 80), mapping = aes(x = t3_reading, y = tsh_reading, color = thyroid_class)) + geom_point() 

plotly::ggplotly(p)
```


