---
title: "Dashboard"
author: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    vertical_layout: scroll
    smooth_scroll: true
runtime: shiny
---


```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)
library(readr)
library(shiny)
library(stringr)

thyroid <- read.csv("thyroid.csv", header=TRUE, colClasses = 
                   c("ThryroidClass" = "character",
                     "patient_gender" = "character",
                     "presc_thyroxine" = "character",
                     "queried_why_on_thyroxine" = "character",
                     "presc_anthyroid_meds" = "character",
                     "sick" = "character",
                     "pregnant" = "character",
                     "thyroid_surgery" = "character",
                     "radioactive_iodine_therapyI131" = "character",
                     "query_hypothyroid" = "character",
                     "query_hyperthyroid" = "character",
                     "lithium" = "character",
                     "goitre" = "character",
                     "tumor" = "character",
                     "hypopituitarism" = "character",
                     "psych_condition" = "character",
                     "TSH_measured" = "character",
                     "T3_measured" = "character",
                     "T4_measured" = "character",
                     "thyrox_util_rate_T4U_measured" = "character",
                     "FTI_measured" = "character",
                     "ref_src" = "character")
                 )

colnames(thyroid)[1] <- 'thyroid_class'
```


Infos
=======================================================================
Row {.tabset}
-----------------------------------------------------------------------

### Informations data

```{r}
skimr::skim(thyroid)

```


### Informations patients


```{r}

```


```{r}

```

### Autre

```{r}

```







Comparing Groups
=======================================================================


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('xcol', 'X Variable', names(thyroid), selected=names(thyroid)[[2]])
    
selectInput('ycol', 'Y Variable', names(thyroid), selected=names(thyroid)[[21]])

selectInput('grp', 'Group', c('None', names(thyroid)), selected=names(thyroid)[[1]])

```

Column
-----------------------------------------------------------------------



```{r}


plotly::renderPlotly({
  p <- ggplot(thyroid, mapping = aes(x=UQ(as.name(input$xcol)), y=UQ(as.name(input$ycol)))) + 
    geom_point() + 
    labs(x = str_to_title(str_replace(input$xcol, "_", " ")) ,y = str_to_title(str_replace(input$ycol, "_", " ")))
  
  if (input$grp != 'None')
    p <- p + aes_string(color=input$grp)
  
  print(plotly::ggplotly(p))
  
})

```























